= Zsh dot files

Zsh configuration files.

Requires https://github.com/sorin-ionescu/prezto[prezto^] installation first.

== Installation

. Install https://github.com/sorin-ionescu/prezto[prezto^]
. create links to the zsh/prezto conf files in this folder (and replace the ones created by prezto install)

	setopt EXTENDED_GLOB
	ln -s ~/dotfiles/zsh/zprofile ${ZDOTDIR:-$HOME}/.zprofile
	ln -s ~/dotfiles/zsh/zshrc ${ZDOTDIR:-$HOME}/.zshrc
	ln -s ~/dotfiles/zsh/zpreztorc ${ZDOTDIR:-$HOME}/.zpreztorc

. copy the custom prompt function (if any) in ~/.zprezto/modules/prompt; Example:

	# single file
	ln -s ~/dotfiles/zsh/prompt_functions/prompt_ajo1_setup ~/.zprezto/modules/prompt/functions/prompt_ajo1_setup

	# multiple files
	setopt EXTENDED_GLOB
	for promptfile in ~/Projects/Perso/dotfiles/zsh/prompt_functions/*; do
		ln -s "$promptfile" "${ZDOTDIR:-$HOME}/.zprezto/modules/prompt/functions/${promptfile:t}"
	done


== Alternative prompt (theme)

.There are many great themes out there:
* https://github.com/Chauncey-Garrett/zsh-prompt-garrett/

== Updating Prezto

You can update prezto as documented https://github.com/sorin-ionescu/prezto#updating[here^]

	cd ~/.zprezto
	git pull && git submodule update --init --recursive

Don't forget to re-link your custom prompt (if any):

	ln -s ~/dotfiles/zsh/prompt_functions/prompt_ajo1_setup ~/.zprezto/modules/prompt/functions/prompt_ajo1_setup
