#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

## ==== PowerLevel 9K config ===
# zpresto Powerlevel9K prompt config (see https://github.com/bhilburn/powerlevel9k#prompt-customization)
# check colors here https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt or here https://jonasjacek.github.io/colors/
# iTerm Font: Meslo Nerd Font Complete
# iTerm color theme: NightLion v2
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs ssh)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_DIR_HOME_BACKGROUND='lightslategrey'
POWERLEVEL9K_DIR_HOME_FOREGROUND='grey19'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='lightslategrey'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='grey19'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='lightslategrey'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='grey19'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='071'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='sandybrown'
##

## ==== Spaceship prompt config ===
SPACESHIP_VI_MODE_SHOW=false
SPACESHIP_PACKAGE_SHOW=false
##

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Unset AUTO_NAME_DIRS to disable display of variables in path (see module directory)
unsetopt AUTO_NAME_DIRS

# Aliases

# JDK
#alias jdk6='export JAVA_HOME=`/usr/libexec/java_home -v 1.6`; java -version'
#alias jdk7='export JAVA_HOME=`/usr/libexec/java_home -v 1.7`; java -version'
alias jdk8='export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version'

# Sublime text
alias st="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'"
alias stt='st .'

# Go lang (installed with Homebrew)
#DON'T USE SYMLINK ! export GOROOT=/usr/local/opt/go
export GOROOT=/usr/local/Cellar/go/1.11.4/libexec
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/Projects/go

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# OS X: Show/hide hidden files in Finder
alias show_hidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide_hidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
# OS X: Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

# shortcuts to some of my utils (requires local build)
#alias jarfinderP='python ~/Dev/Python/Utils/jarfinder.py'
alias jarfinder='java -cp ~/Dev/Workspaces/AJO/PersoProjects/ozb-jartools/target/scala-2.10/ozb-jartools-dist-0.2.jar org.ozb.utils.jartools.JarFinder'
alias jargrep='java -cp ~/Dev/Workspaces/AJO/PersoProjects/ozb-jartools/target/scala-2.10/ozb-jartools-dist-0.2.jar org.ozb.utils.jartools.JarGrep'
alias dropboxUpload='~/Projects/Perso/ozb-dropbox-upload/target/universal/stage/bin/ozb-dropbox-upload'

# commands to open various tools
#alias vdiff="open -a 'Araxis Merge'"
alias vdiff="open -a 'Kaleidoscope'"
alias vzip="open -a betterzip"

# not needed anymore with zsh, use http-serve instead.
#alias httpServer="python -m SimpleHTTPServer 8080"

# show full file path (bash)
#alias filepath="python -c 'import os,sys;print os.path.realpath(sys.argv[1])'"
# show full file path (zsh)
filepath() { for f in "$@"; do echo ${f}(:A); done }

# OS X: restart airport
alias restart_airport="sudo ifconfig en0 down; sleep 2; sudo ifconfig en0 up"

# Directory aliases
alias pprj="cd ~/Projects/Perso"

# WorkingOn service function (see https://www.workingon.co/tools#cli-bash-zsh)
function workingOn() { noglob curl -X POST --data-urlencode "task=$*" https://api.workingon.co/hooks/incoming?token=dbd0d6c48351a8ab86130333559e5c1466b05f462a3a5663205576b632330cd3 >/dev/null 2>&1 echo "Task sent." }

#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Python 3 with virtualenvwrapper
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export WORKON_HOME="~/.virtualenvs"
[ -f /usr/local/bin/virtualenvwrapper.sh ] && source /usr/local/bin/virtualenvwrapper.sh
source `npm root -g`/zsh-history-enquirer/scripts/zsh-history-enquirer.plugin.zsh
